name: besoins
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^16.0.0
  path_provider: ^2.1.5
  collection: ^1.19.1
  fl_chart: ^0.68.0
  table_calendar: ^3.1.1
  pdf: ^3.11.3
  excel: ^4.0.6
  intl: ^0.19.0
  speech_to_text: ^7.1.0
  
  # Hive dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  
  # Hive generator
  hive_generator: ^2.0.1
  analyzer: ^5.13.0 # Keep analyzer for other generators if any
  flutter_launcher_icons: "^0.13.1" # Added flutter_launcher_icons

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
